1. What is a Python library? Why do we use Python libraries?

Ans-A Python library is a collection of pre-written code that provides functionalities and tools for various tasks. These libraries are essentially modules that you can import into your Python programs to use their functionalities without having to write the code from scratch. They can include functions, classes, and variables that help streamline development and make it easier to perform complex tasks.

Here’s why we use Python libraries:

1. **Code Reusability**: Libraries allow you to reuse code, which can save time and effort. Instead of writing the same functionality repeatedly, you can use libraries that have already implemented it.

2. **Efficiency**: Many libraries are optimized and tested, so they can perform tasks more efficiently than custom code. This helps in improving the performance and reliability of your programs.

3. **Complex Functionality**: Some libraries provide complex functionalities and algorithms that would be challenging and time-consuming to develop from scratch. For instance, libraries like TensorFlow or scikit-learn offer advanced machine learning capabilities.

4. **Community Support**: Popular libraries often have strong community support, which means you can find documentation, tutorials, and forums to help you use them effectively.

5. **Standardization**: Libraries often follow best practices and standards, which helps in writing consistent and maintainable code.

6. **Focus on Core Logic**: By using libraries, you can focus on the core logic and unique features of your application rather than reinventing the wheel for common functionalities.



2. What is the difference between Numpy array and List?

Here’s a concise comparison:

- **Python List**:
  - Can hold mixed data types.
  - Slower for numerical operations.
  - Limited to basic operations and lacks advanced mathematical functions.
  - Less memory-efficient.

- **NumPy Array**:
  - Holds elements of the same data type.
  - Faster and more efficient for numerical operations.
  - Provides a wide range of mathematical and array operations.
  - More memory-efficient and supports multi-dimensional arrays.



3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [1]:
import numpy as np

# Define the array
array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Get the shape of the array
shape = array.shape

# Get the size of the array
size = array.size

# Get the number of dimensions of the array
dimensions = array.ndim

# Print the results
print("Shape:", shape)
print("Size:", size)
print("Dimensions:", dimensions)


Shape: (3, 4)
Size: 12
Dimensions: 2


4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [2]:
import numpy as np

# Define the array
array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Access the first row
first_row = array[0]

# Print the result
print("First row:", first_row)


First row: [1 2 3 4]


5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [3]:
import numpy as np

# Define the array
array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Access the element at the third row and fourth column
# Note: Indexing starts at 0, so third row is index 2 and fourth column is index 3
element = array[2, 3]

# Print the result
print("Element at third row and fourth column:", element)


Element at third row and fourth column: 12


6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [4]:
import numpy as np

# Define the array
array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Extract all odd-indexed elements
# Note: Odd indices are 1 and 3 for both rows and columns
odd_indexed_elements = array[::2, ::2]

# Print the result
print("Odd-indexed elements:\n", odd_indexed_elements)


Odd-indexed elements:
 [[ 1  3]
 [ 9 11]]


7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [7]:
import numpy as np

# Generate a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)

# Print the result
print("Random 3x3 matrix with values between 0 and 1:\n", random_matrix)


Random 3x3 matrix with values between 0 and 1:
 [[0.27929075 0.27550281 0.55035777]
 [0.43429079 0.91688298 0.36339282]
 [0.47342065 0.12462543 0.58404114]]


8. Describe the difference between np.random.rand and np.random.randn?

Ans- np.random.rand(d1, d2, ...): Generates random numbers uniformly distributed between 0 and 1.

np.random.randn(d1, d2, ...): Generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1).

9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [8]:
import numpy as np

# Define the original array
array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Increase the dimension by adding a new axis
expanded_array = np.expand_dims(array, axis=0)  # Adds a new dimension at position 0

print("Expanded array with np.expand_dims:\n", expanded_array)
print("New shape:", expanded_array.shape)


Expanded array with np.expand_dims:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
New shape: (1, 3, 4)


10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [9]:
import numpy as np

# Define the array
array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Transpose the array using .T
transposed_array = array.T

print("Transposed array using .T:\n", transposed_array)


Transposed array using .T:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python1
,+ Index wise multiplicatio'
]+ Matrix multiplicatio'
+ Add both the matricK
-+ Subtract matrix B from
+ Divide Matrix B by A

In [10]:
import numpy as np

# Define the matrices
A = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

B = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Index-wise Multiplication
index_wise_multiplication = A * B

# Matrix Multiplication
matrix_multiplication = np.dot(A, B.T)  # Transpose B to match dimensions for matrix multiplication

# Add Both Matrices
addition = A + B

# Subtract Matrix B from A
subtraction = A - B

# Divide Matrix B by A
# Note: Division will result in a warning if there are zeros in A, but here A has no zeros
division = B / A

# Print results
print("Index-wise Multiplication:\n", index_wise_multiplication)
print("\nMatrix Multiplication:\n", matrix_multiplication)
print("\nAddition of Matrices:\n", addition)
print("\nSubtraction of Matrix B from A:\n", subtraction)
print("\nDivision of Matrix B by A:\n", division)


Index-wise Multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

Matrix Multiplication:
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

Addition of Matrices:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Subtraction of Matrix B from A:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Division of Matrix B by A:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


12. Which function in Numpy can be used to swap the byte order of an array?

Ans-
In NumPy, you can use the .byteswap() method to swap the byte order of an array. This is particularly useful when dealing with data that has different byte orders, such as when reading binary files written on systems with different endianness.

13. What is the significance of the np.linalg.inv function?

Ans- Square Matrix: The matrix must be square (i.e., have the same number of rows and columns) for an inverse to exist.
Invertibility: Not all matrices have an inverse. A matrix must be non-singular (i.e., its determinant must be non-zero) for an inverse to exist.
Numerical Stability: For large or nearly singular matrices, numerical methods for computing inverses may be unstable or inaccurate. In such cases, other methods like pseudo-inverse or decomposition methods (e.g., LU decomposition) may be more appropriate.

14. What does the np.reshape function do, and how is it used?

In [11]:
# The np.reshape function in NumPy is used to change the shape of an array
# without changing its data. It allows you to rearrange the elements of an
# array into a new shape, as long as the total number of elements remains
#  the same.
import numpy as np

# Create a 1D array
array = np.arange(12)  # An array with elements [0, 1, 2, ..., 11]

# Reshape the array to a 2D array with shape (3, 4)
reshaped_array = np.reshape(array, (3, 4))

print("Original array:")
print(array)

print("\nReshaped array (3x4):")
print(reshaped_array)

# Another way to reshape using the .reshape method of the array object
reshaped_array_alt = array.reshape(3, 4)

print("\nReshaped array using .reshape method:")
print(reshaped_array_alt)


Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped array using .reshape method:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


15. What is broadcasting in Numpy?

Ans- Broadcasting in NumPy is a powerful feature that allows you to perform arithmetic operations on arrays of different shapes in a way that is both efficient and intuitive. Broadcasting automatically expands the dimensions of smaller arrays to match the shape of larger arrays, enabling element-wise operations between arrays that do not have the same shape.